version: "3.3"

services:
  mysql: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'technical'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - test-net
  server:
    build: ./server/
    volumes:
      - "./server:/var/www/server"
    ports:
      - "5221:5221"
    networks:
      - test-net
    depends_on:
      - mysql
networks:
  test-net:
    driver: bridge
